package gov.tceq.epay.webservice.epay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-06T18:11:06.601+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://webservice.epay.tceq.gov/epay", name = "EpayPortType")
@XmlSeeAlso({gov.tceq.epay.webservice.xsd.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EpayPortType {

    @WebMethod(action = "epayUserLogout")
    @WebResult(name = "EpayUserLogoutResponse", targetNamespace = "http://webservice.epay.tceq.gov/xsd", partName = "epayUserLogoutResponse")
    gov.tceq.epay.webservice.xsd.EpayUserLogoutResponse epayUserLogout(
            @WebParam(partName = "epayUserLogout", name = "EpayUserLogout", targetNamespace = "http://webservice.epay.tceq.gov/xsd")
                    gov.tceq.epay.webservice.xsd.EpayUserLogout epayUserLogout
    ) throws ErrorResponse;

    @WebMethod(action = "epayLoadBilledFees")
    @WebResult(name = "EpayLoadBilledFeesResponse", targetNamespace = "http://webservice.epay.tceq.gov/xsd", partName = "epayLoadBilledFeesResponse")
    gov.tceq.epay.webservice.xsd.EpayLoadBilledFeesResponse epayLoadBilledFees(
            @WebParam(partName = "epayLoadBilledFees", name = "EpayLoadBilledFees", targetNamespace = "http://webservice.epay.tceq.gov/xsd")
                    gov.tceq.epay.webservice.xsd.EpayLoadBilledFees epayLoadBilledFees
    ) throws ErrorResponse;

    @WebMethod(action = "epayGetStatus")
    @WebResult(name = "EpayGetStatusResponse", targetNamespace = "http://webservice.epay.tceq.gov/xsd", partName = "epayGetStatusResponse")
    gov.tceq.epay.webservice.xsd.EpayGetStatusResponse epayGetStatus(
            @WebParam(partName = "epayGetStatus", name = "EpayGetStatus", targetNamespace = "http://webservice.epay.tceq.gov/xsd")
                    gov.tceq.epay.webservice.xsd.EpayGetStatus epayGetStatus
    ) throws ErrorResponse;

    @WebMethod(action = "epayGetStatusByVoucher")
    @WebResult(name = "EpayGetStatusByVoucherResponse", targetNamespace = "http://webservice.epay.tceq.gov/xsd", partName = "epayGetStatusByVoucherResponse")
    gov.tceq.epay.webservice.xsd.EpayGetStatusByVoucherResponse epayGetStatusByVoucher(
            @WebParam(partName = "epayGetStatusByVoucher", name = "EpayGetStatusByVoucher", targetNamespace = "http://webservice.epay.tceq.gov/xsd")
                    gov.tceq.epay.webservice.xsd.EpayGetStatusByVoucher epayGetStatusByVoucher
    ) throws ErrorResponse;

    @WebMethod(action = "epayLoadShoppingCart")
    @WebResult(name = "EpayLoadShoppingCartResponse", targetNamespace = "http://webservice.epay.tceq.gov/xsd", partName = "epayLoadShoppingCartResponse")
    gov.tceq.epay.webservice.xsd.EpayLoadShoppingCartResponse epayLoadShoppingCart(
            @WebParam(partName = "epayLoadShoppingCart", name = "EpayLoadShoppingCart", targetNamespace = "http://webservice.epay.tceq.gov/xsd")
                    gov.tceq.epay.webservice.xsd.EpayLoadShoppingCart epayLoadShoppingCart
    ) throws ErrorResponse;

    @WebMethod(action = "epayUpdateVoucherStatus")
    @WebResult(name = "EpayUpdateVoucherStatusResponse", targetNamespace = "http://webservice.epay.tceq.gov/xsd", partName = "epayUpdateVoucherStatusResponse")
    gov.tceq.epay.webservice.xsd.EpayUpdateVoucherStatusResponse epayUpdateVoucherStatus(
            @WebParam(partName = "epayUpdateVoucherStatus", name = "EpayUpdateVoucherStatus", targetNamespace = "http://webservice.epay.tceq.gov/xsd")
                    gov.tceq.epay.webservice.xsd.EpayUpdateVoucherStatus epayUpdateVoucherStatus
    ) throws ErrorResponse;

    @WebMethod(action = "epayUserLogin")
    @WebResult(name = "EpayUserLoginResponse", targetNamespace = "http://webservice.epay.tceq.gov/xsd", partName = "epayUserLoginResponse")
    gov.tceq.epay.webservice.xsd.EpayUserLoginResponse epayUserLogin(
            @WebParam(partName = "epayUserLogin", name = "EpayUserLogin", targetNamespace = "http://webservice.epay.tceq.gov/xsd")
                    gov.tceq.epay.webservice.xsd.EpayUserLogin epayUserLogin
    ) throws ErrorResponse;

    @WebMethod(action = "epayGetPayments")
    @WebResult(name = "EpayGetPaymentsResponse", targetNamespace = "http://webservice.epay.tceq.gov/xsd", partName = "epayGetPaymentsResponse")
    gov.tceq.epay.webservice.xsd.EpayGetPaymentsResponse epayGetPayments(
            @WebParam(partName = "epayGetPayments", name = "EpayGetPayments", targetNamespace = "http://webservice.epay.tceq.gov/xsd")
                    gov.tceq.epay.webservice.xsd.EpayGetPayments epayGetPayments
    ) throws ErrorResponse;

    @WebMethod(action = "epayPing")
    @WebResult(name = "EpayPingResponse", targetNamespace = "http://webservice.epay.tceq.gov/xsd", partName = "epayPingResponse")
    gov.tceq.epay.webservice.xsd.EpayPingResponse epayPing(
            @WebParam(partName = "epayPing", name = "EpayPing", targetNamespace = "http://webservice.epay.tceq.gov/xsd")
                    gov.tceq.epay.webservice.xsd.EpayPing epayPing
    ) throws ErrorResponse;
}
