
package gov.tceq.epay.webservice.epay;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-06T18:11:06.521+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "ErrorResponse", targetNamespace = "http://webservice.epay.tceq.gov/xsd")
public class ErrorResponse extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private gov.tceq.epay.webservice.xsd.EpayError errorResponse;

    public ErrorResponse() {
        super();
    }
    
    public ErrorResponse(String message) {
        super(message);
    }
    
    public ErrorResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ErrorResponse(String message, gov.tceq.epay.webservice.xsd.EpayError errorResponse) {
        super(message);
        this.errorResponse = errorResponse;
    }

    public ErrorResponse(String message, gov.tceq.epay.webservice.xsd.EpayError errorResponse, Throwable cause) {
        super(message, cause);
        this.errorResponse = errorResponse;
    }

    public gov.tceq.epay.webservice.xsd.EpayError getFaultInfo() {
        return this.errorResponse;
    }
}
